global:
  scrape_interval: 5s
  evaluation_interval: 15s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'myapp'
    scrape_interval: 2s
    static_configs:
      - targets: ['myapp:8080']
