FROM quarkus/base

LABEL org.label-schema.description="UBI8-minimal image for Quarkus native" \
      org.label-schema.name=quarkus-native \
      org.label-schema.version=${project.version} \
      org.label-schema.vcs-url=${git.remote.origin.url} \
      org.label-schema.vcs-ref=${git.commit.id}

EXPOSE 8080
USER nobody


